### ISSUE TITLE
数据质量 

### ISSUE THREAD

**Issue by findalexli** [yixuantt/MultiHop-RAG#11]
用肉眼看看这个数据集里面的问题 我看了一些 感觉可能30%还是不错的问题 但是很多是这样的

Which company, as reported by both TechCrunch and The Verge, has spent billions to maintain its default search engine status on various platforms and is also accused of harming news publishers\u2019 revenue through its business practices
anser: Google
What is the name of the organization discussed in TechCrunch articles that, despite its financial instability, is recognized for creating ChatGPT, which is both a priority and a platform for ongoing innovations, and is planning to enhance its capabilities with the release of GPT-4 and associated APIs?
answer openai
就是只需要一个evidence就可以回答了 那这个就没有检测到系统multi hop的能力，实际上只需要一个hop

在comparions里面 我觉得比较一般的是这种
Does 'The Age' article suggest that Australia's Davis Cup team is aiming for an improvement in their performance compared to the previous year, while the 'Sporting News' article indicates that the South Africa national rugby team has already achieved an improvement to reach the Rugby World Cup semi-finals? answer yes 这个推理的话就是简单的在两个文章中推理出两个yes 两个yes所以答案是yes
"Does the Sporting News article suggest that streaming services do not require a subscription for viewing the Cowboys vs. 49ers game, in contrast to the Polygon article's claim about film availability on streaming platforms without a subscription?"

这个问题问的两个entity 是无关的 前半个是一个体育节目的 后半个就笼统的再讲电影在那个streaming 平台可以无订阅费看。

我觉得比较好的问题是同一个entity 在两个来源中提出 要同时看两个来源 （比如冷热这个entity，在一个北极和在新疆）

但是瞄了一眼大部分都是不同的entity，推理主要都是分开的

**Comment by yixuantt** [comment]
Hello. 
关于前两个问题示例，是基于“并”，所以模型其实是需要检查多个子问题是不是都成立。
关于comparions，这样两个比较无关的entity确实存在，但是我们构建数据集的第一步就是筛选entity和topic，尽量保证用来构建问题的entity是同一个。我想仍然存在无关entity的原因是我们去掉了来自不同source但是语义相似的句子，这样能保证检查evidence时不会有干扰项。

By the way，虽然目前可能GPT生成的问题质量并不完美，但是我想仍然可以作为一个不错的benchmark，并且目前LLM的表现确实也欠佳。

**Comment by findalexli** [comment]
感谢回答 我觉得可能更高质量的是需要sequential dependency的 比如第一步需要知道一个东西是什么 第二步带着前者的知识做下一步的查找 我在论文中inference 这一块读到是这个感觉，但是可能数据里面主要是单独的判断，子问题和子问题之间，只有在最后有逻辑上的一个比较简单的合并/相互confirm，而不是有‘hop’的因果

有没有考虑进一步筛选出less and higher quality subset?

**Comment by yixuantt** [comment]
是的，因为构建数据集时关注点在Retrieval时需要多个evidence。

谢谢你的comments，等我有时间了我会想办法构建一个higher quality dataset 🤔

**Comment by yixuantt** [comment]
BTW, 如果你有兴趣的话欢迎合作！

**Comment by findalexli** [comment]
好呀 我们在想做multi hop rag方法 可以加个微信? li_shengzhi
