### ISSUE TITLE
the answer “no” mean “no change” or “no no change”?

### ISSUE THREAD

**Issue by superccy** [yixuantt/MultiHop-RAG#12]
Your work is very interesting. 
I noticed that there is a type of question that asks whether there is any change or impact. The answer is no. But I don't know whether this no means no change or yes change.

Here is an example：

Q：Was there no change in the portrayal of Sam Altman's professional conduct between the TechCrunch report on Sam Altman's involvement with a teen's AI startup published on October 7, 2023, and the TechCrunch report suggesting Sam Altman was being fully truthful with the board published on November 18, 2023?
A: no

Does this "no" mean no change or yes change? Thank you

**Comment by yixuantt** [comment]
Hi. The "no" means yes change. Maybe this is a little ambiguous.

**Comment by superccy** [comment]
> Hi. The "no" means yes change. Maybe this is a little ambiguous.

Thank you very much. The answer "no" to all questions in this type means yes change, right?

**Comment by yixuantt** [comment]
yes， you are right.

**Comment by superccy** [comment]
ok, thank you very much.
