### ISSUE TITLE
qa_evaluate

### ISSUE THREAD

**Issue by songsey** [yixuantt/MultiHop-RAG#15]
Shouldn't we use an LLM judge to evaluate the accuracy? Yes, I can create my own, but I'm wondering why the provided code uses token overlaps.

**Comment by yixuantt** [comment]
Yes, I also tried the LLM as a judge. However, the code is not provided here as the paper uses exact matching. (The results are also very close)

**Comment by songsey** [comment]
can you please provide the prompt you used for evaluation? and what LLM you used?

**Comment by yixuantt** [comment]
I let the LLM verify if these two answers are the same (ground truth; response) using GPT-4 Turbo. Answer yes/no

**Comment by songsey** [comment]
Evaluated the QA_LLaMA-generated responses with `step1_data.json`, while the generation model was changed to GPT-4o-mini. This is the response with retrieval in your paper. I used an LLM judge with a prompt similar to what you mentioned above, and the accuracy of GPT-4o-mini is near 1.

**Comment by yixuantt** [comment]
Did you use the retrieved chunks or gold chunks?

**Comment by songsey** [comment]
It should be retreived chunks if I use `qa_llama.py` ?

**Comment by yixuantt** [comment]
Yes. But this is amazing because the retrieved chunks are not complete. likely because step1_data.json is a toy dataset and lacks the full testing samples. Maybe the full testing samples will be different.  How about the token overlaps?

**Comment by songsey** [comment]
It seems to me it's because of how the gold answer and model answer are processed in `qa_evaluate`. When we use an LLM judge, can we just use...
```
model_answer = d['model_answer']
gold=d['gold_answer']
```
?

**Comment by yixuantt** [comment]
Sure.

**Comment by songsey** [comment]
Just in case, I checked the code, and it’s not the issue. The GPT-4o-mini generated responses with retrieved chunks for `inference_query` type questions, even with a single RAG, are quite high. I asked because the `inference_query` accuracy with retrieved chunks being very high in a simple RAG system goes against the objective of building the dataset.

**Comment by yixuantt** [comment]
Oh. I got it. The inference accuracy of the GPT-4 Turbo I tested is also very high, but it is low for comparison and temporal queries. I also planned to enhance the entire query with the more powerful GPT-4o, making it more challenging. But thanks for your observation.

**Comment by songsey** [comment]
comparison_query and temporal_query seem to have higher value in the benchmark, even for large models like GPT-4o-mini. This seems to show that they remain challenging tasks, even for such models. Additionally, large LLMs tend to hallucinate less, as demonstrated in the null query, as mentioned in the paper. GPT-4o models perform quite well on the other two types of queries, even with a simple RAG system with a retrieval depth of 5.

**Comment by yixuantt** [comment]
Great. Glad to hear some feedback!
