### ISSUE TITLE
Make public evaluation code

### ISSUE THREAD

**Issue by chubzchubz97** [yixuantt/MultiHop-RAG#4]
Hi, would you please consider making public the code to reproduce the results in your paper? Thanks!

**Comment by yixuantt** [comment]
Hi, the evaluation code has already been made public. Please check the evaluate.py.

**Comment by hugoabonizio** [comment]
@yixuantt I believe `evaluate.py` evaluates only the retrieval results, not the final task itself (question answering accuracy from Table 6).

**Comment by yixuantt** [comment]
@hugoabonizio  Hi Hugo, you can check the qa_llama.py, which I updated. This is a demo script of my question-answering process.

**Comment by Jenna-Che** [comment]
@hugoabonizio Hi, how did you calculate the Accuracy for Table 6? Could you provide a formula? just estimate whether the gold-answer is in the model_answer ?

**Comment by yixuantt** [comment]
closed as the evaluation code has been public.
